apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootbasic-deployment
  namespace: mynamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springbootbasic
  template:
    metadata:
      labels:
        app: springbootbasic
    spec:
      containers:
      - name: springbootbasic
        image: abhishekbit96/springbootbasic:latest
        ports:
        - containerPort: 1996
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 1996
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 1996
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: springbootbasic-service
  namespace: mynamespace
spec:
  type: LoadBalancer
  selector:
    app: springbootbasic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080