name: Build, Push Docker Image, and Deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  prevalidation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Maven configuration
      run: mvn validate

  checkout:
    runs-on: ubuntu-latest
    needs: prevalidation
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  setup_jdk:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

  build_maven:
    runs-on: ubuntu-latest
    needs: setup_jdk
    steps:
      - name: List files for debugging
        run: ls -R

      - name: Find pom.xml
        id: find-pom
        run: |
          echo "Current path: $(pwd)"
          echo "Listing all files:"
          ls -R
          POM_PATH=$(find . -name "pom.xml" | head -n 1)
          echo "POM_PATH=$POM_PATH" >> $GITHUB_ENV
          echo "POM_PATH=$POM_PATH"

      - name: Build with Maven
        run: mvn -f ${{ env.POM_PATH }} clean package

  docker_login:
    runs-on: ubuntu-latest
    needs: build_maven
    steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  build_push_docker:
    runs-on: ubuntu-latest
    needs: docker_login
    steps:
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springbootbasic:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/springbootbasic:${{ github.sha }}

  setup_k8s:
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: 'latest'

  deploy_k8s:
    runs-on: ubuntu-latest
    needs: setup_k8s
    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/springbootbasic springbootbasic=${{ secrets.DOCKER_USERNAME }}/springbootbasic:${{ github.sha }}